epochs: 150
batch_size_train: 2
batch_size_test: 10
nb_batch_per_epoch: 1
train_sampler: null
validation_sampler: null
time_features: null
trainer_kwargs:
    max_epochs: ${train.epochs}
    limit_train_batches: ${train.batch_size_train}
    gradient_clip_val : 10.
callback:
  _target_: domain.callbacks.MetricsCallback
