epochs: 1000
batch_size_train: 128 # must be exponent of 2
batch_size_test: 32
nb_batch_per_epoch: 100 # keep as it
train_sampler: null
validation_sampler: null
time_features: null
trainer_kwargs:
    max_epochs: ${train.epochs}
    limit_train_batches: ${train.batch_size_train}
    gradient_clip_val : 10.
callback:
  _target_: utils.tensorboard_logging.MetricsCallback
