epochs: 10000
batch_size_train: 512 # must be exponent of 2
batch_size_test: 2
nb_batch_per_epoch: 100 # keep as it
train_sampler: null
validation_sampler: null
time_features: null
trainer_kwargs:
    max_epochs: ${train.epochs}
    gradient_clip_val: 10.
callback:
  _target_: utils.training_logging.MetricsCallback
