model_name: Informer
model_config:
  input_size: 1
  prediction_length : 7
  context_length : 28
  lags_sequence:
    - 1
    - 168 # 7*24
  dropout: 0.1
  num_heads:  4
  variable_dim: null
  encoder_layers: 1
  decoder_layers: 1
  d_models: 64
  scaling: mean
  num_parallel_samples: 100
  cardinality: [1]
optimizer_config:
  lr: 0.0006
  betas: [0.9, 0.95]
  weight_decay: 0.1
