defaults:
  - _self_
  - model_config: lgbm_default
  - features: default

model_name: SklearnForecaster
model_config:
  _target_: lightgbm.LGBMRegressor
  prediction_length: ${dataset.load.prediction_length}
  freq_increm: ${dataset.freq_increm}
target: ${dataset.load.target}
date_col: date
error_metrics:
  - mae
  - rmse
  - smape
  - wmape
cv_config:
  unit: D
  training_minimum_window: 60
  test_window: 30
