defaults:
  - _self_
  - pipeline: default

pipeline:
  Create_calendar_features:
    _target_: domain.feature_engineering.calendar_features.CalendarFeatures
    column_name: date
  Create_holidays_features:
    _target_: domain.feature_engineering.calendar_features.AddHolidays
    date_col: date
    config_country_holidays:
      country: FR
      subdiv: Métropole
    replace_values: ${_constants.holidaysrenaming}
    year_start: 2018
    year_end: 2024
    features:
      - isholiday
      - is_vacances_zone=B
      - is_vacances_zone=C
  Create_lagsfeatures:
    _target_: domain.feature_engineering.lags_features.LagsFeatures
    column_name:  ${dataset.load.target}
    date_col: date
    lags:
      - ${eval:'${model.model_config.prediction_length}'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*4'}D
    groupers:
      - item_id
  Create_lagsfeatures_week:
    _target_: domain.feature_engineering.lags_features.LagsFeatures
    column_name:  ${dataset.load.target}
    date_col: date
    lags:
      - ${eval:'${model.model_config.prediction_length}'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*4'}D
    groupers:
      - item_id
      - day
  Create_lagsfeatures_imaginer:
    _target_: domain.feature_engineering.lags_features.LagsFeatures
    column_name: NB_VALD=IMAGINE_R
    date_col: date
    lags:
      - ${eval:'${model.model_config.prediction_length}'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*4'}D
    groupers:
      - item_id
  Create_lagsfeatures_navigo:
    _target_: domain.feature_engineering.lags_features.LagsFeatures
    column_name: NB_VALD=NAVIGO
    date_col: date
    lags:
      - ${eval:'${model.model_config.prediction_length}'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*4'}D
    groupers:
      - item_id
  Create_lagsfeatures_navigojour:
    _target_: domain.feature_engineering.lags_features.LagsFeatures
    column_name: NB_VALD=NAVIGO_JOUR
    date_col: date
    lags:
      - ${eval:'${model.model_config.prediction_length}'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*4'}D
    groupers:
      - item_id
  Create_lagsfeatures_AMETHYSTE:
    _target_: domain.feature_engineering.lags_features.LagsFeatures
    column_name: NB_VALD=AMETHYSTE
    date_col: date
    lags:
      - ${eval:'${model.model_config.prediction_length}'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*4'}D
    groupers:
      - item_id
  Create_roll_mean_features:
    _target_: domain.feature_engineering.lags_features.RollingFeatures
    column_name: ${dataset.load.target}_prev=${model.model_config.prediction_length}D
    date_col: date
    min_periods: 7
    aggregate_func_name : mean
    groupers:
      - item_id
      - dayofweek
    lags:
      - ${eval:'${model.model_config.prediction_length}'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*4'}D
  Create_roll_median_features:
    _target_: domain.feature_engineering.lags_features.RollingFeatures
    column_name: ${dataset.load.target}_prev=${model.model_config.prediction_length}D
    date_col: date
    min_periods: 7
    aggregate_func_name : median
    groupers:
      - item_id
      - dayofweek
    lags:
      - ${eval:'${model.model_config.prediction_length}'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D
      - ${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*4'}D
      

train_test_pred:
  date_col: date
  date_start_train: 2016-01-01
  date_split_train_test: 2019-10-${eval:'30 - ${model.model_config.prediction_length}'}
  date_split_test_pred: 2019-10-${eval:'30 - ${model.model_config.prediction_length}'}
  split_variable: null


item_id_list: ${dataset.name_feats.feat_for_item_id}