name: dl4tsf
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel=6.4.1
  - lightgbm=3.2.1
  - matplotlib=3.5.2
  - pip=21.2.4
  - pip:
      - accelerate==0.18.0
      - azure==4.0.0
      - azure-storage-blob==12.16.0
      - boto3==1.26
      - datasets==2.10.1
      - evaluate==0.4.0
      - geopy==2.3.0
      - gluonts==0.12.5
      - hydra-core==1.3.1
      - importlib-metadata==4.13.0
      - isort==5.12.0
      - jupytext==1.14.5
      - mlflow==2.2.2
      - mxnet==1.9.1
      - notebook==6.5.2
      - numpy==1.21.6
      - openpyxl==3.1.1
      - osmnx==1.4.0
      - pandas==1.3.5
      - pre-commit==2.21.0
      - protobuf==3.20.3
      - pydantic==1.10.4
      - pytorch-lightning==2.0.0
      - rich==13.3.3
      - tensorboard==2.13.0
      - tokenizers==0.13.2
      - transformers==4.27.3
      - ujson==5.7.0
  - python=3.8
  - seaborn=0.11.2
