holidaysrenaming:
  AbolitionEsclavage:
    - Abolition de l'esclavage
  ArafatDay:
    - Arafat Day
  Armistice1918France:
    - Armistice 1918
  Armistice1945France:
    - Armistice 1945
  Ascension:
    - Ascension
  Assomption:
    - Assomption
    - Assunção de Nossa Senhora
  Carnaval:
    - Carnaval
  Christmas:
    - Noël
    - Dia de Natal
  ChristmasEve:
    - Véspera de Natal
  CommemorationIndependenceMorocco:
    - Commémoration de la présentation du manifeste de l'indépendance
  CorpusChristi:
    - Corpo de Deus
  DayPortugal:
    - Dia de Portugal
  Decembre26:
    - 26 de Dezembro
  Easter:
    - Páscoa
    - Lundi de Pâques
  EidAdha:
    - Eid al-Adha
    - Eid al-Adha Holiday
  EidFitr:
    - Eid al-Fitr
    - Eid al-Fitr Holiday
  EvacuationDay:
    - Evacuation Day
  FridaySaint:
    - Vendredi saint
    - Sexta-feira Santa
  ImmaculateConceptionPortugal:
    - Imaculada Conceição
  IndependenceMorocco:
    - Fête de l'indépendance
  IndependencePortugal:
    - Restauração da Independência
  IndependenceTunisia:
    - Independence Day
  IslamicNewYear:
    - 1er Moharram
    - Islamic New Year
  LabourDay:
    - Labour Day
    - Dia do Trabalhador
    - Fête du Travail
  LastDayYear:
    - Véspera de Ano Novo
  LibertyDay:
    - Dia da Liberdade
  MartyrsDayTunisia:
    - Martyrs' Day
  NationalHolidayMorocco:
    - Fête du Trône
    - Fête du Trône
  NationalHolidayReunion:
    - Fête nationale
  NationalHolidayTunisia:
    - Republic Day
  NewYear:
    - Jour de l'an
    - Dia de Todos os Santos
    - Nouvel an - Premier janvier
    - New Year's Day
    - Ano Novo
  OuedEdDahabTunisia:
    - Journée de Oued Ed-Dahab
  Pentecote:
    - Lundi de Pentecôte
  ProphetBirthdayMorocco:
    - Aid al Mawlid Annabawi
  ProphetBirthdayTunisia:
    - Prophet Muhammad's Birthday
  RepubliquePortugal:
    - Implantação da República
  SaintAntonioPortugal:
    - Dia de Santo António
  Toussaint:
    - Toussaint
  VictorSchoelcherGuadeloupe:
    - Fête Victor Schoelcher
  WomenDayTunisia:
    - Women's Day
  YouthDayTunisia:
    - Revolution and Youth Day - January 14
