# - date
# - item_id
# - STATION
# - NB_VALD=AMETHYSTE # never add this as feature
# - NB_VALD=AUTRE # never add this as feature
# - NB_VALD=FGT # never add this as feature
# - NB_VALD=IMAGINE_R # never add this as feature
# - NB_VALD=NAVIGO # never add this as feature
# - NB_VALD=NAVIGO_JOUR # never add this as feature
# - NB_VALD=TST # never add this as feature
- temperature
- pressure
- rainfall
- amenity_type=Centers
- amenity_type=Education
- amenity_type=Entertainment
- amenity_type=Services
- amenity_type=Sustenance
- amenity_type=Transport
- amenity_type=WorkPlaces
- quarter
- month
- day
- dayofweek
- hour
- week
- isweekend
- isholiday
- season_north=Fall
- season_north=Spring
- season_north=Summer
- season_north=Winter
- season_south=Fall
- season_south=Spring
- season_south=Summer
- season_south=Winter
- is_vacances_zone=B
- is_vacances_zone=C
# classic lags
- VALD_TOTAL_prev=${eval:'${model.model_config.prediction_length}'}D
- VALD_TOTAL_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
- VALD_TOTAL_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
- VALD_TOTAL_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D
# lags with groupers
- VALD_TOTAL_day_prev=${eval:'${model.model_config.prediction_length}'}D
- VALD_TOTAL_day_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
- VALD_TOTAL_day_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
- VALD_TOTAL_day_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D

- NB_VALD=IMAGINE_R_prev=${eval:'${model.model_config.prediction_length}'}D
- NB_VALD=IMAGINE_R_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
- NB_VALD=IMAGINE_R_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
- NB_VALD=IMAGINE_R_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D

- NB_VALD=NAVIGO_prev=${eval:'${model.model_config.prediction_length}'}D
- NB_VALD=NAVIGO_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
- NB_VALD=NAVIGO_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
- NB_VALD=NAVIGO_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D



- NB_VALD=NAVIGO_JOUR_prev=${eval:'${model.model_config.prediction_length}'}D
- NB_VALD=NAVIGO_JOUR_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
- NB_VALD=NAVIGO_JOUR_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
- NB_VALD=NAVIGO_JOUR_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D


- NB_VALD=AMETHYSTE_prev=${eval:'${model.model_config.prediction_length}'}D
- NB_VALD=AMETHYSTE_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
- NB_VALD=AMETHYSTE_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
- NB_VALD=AMETHYSTE_prev=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D

# rolling mean
- VALD_TOTAL_prev=${model.model_config.prediction_length}D_rolling_mean=${eval:'${model.model_config.prediction_length}'}D
- VALD_TOTAL_prev=${model.model_config.prediction_length}D_rolling_mean=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
- VALD_TOTAL_prev=${model.model_config.prediction_length}D_rolling_mean=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
- VALD_TOTAL_prev=${model.model_config.prediction_length}D_rolling_mean=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D

# rolling median
- VALD_TOTAL_prev=${eval:'${model.model_config.prediction_length}'}D_rolling_median=${eval:'${model.model_config.prediction_length}'}D
- VALD_TOTAL_prev=${model.model_config.prediction_length}D_rolling_median=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*1'}D
- VALD_TOTAL_prev=${model.model_config.prediction_length}D_rolling_median=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*2'}D
- VALD_TOTAL_prev=${model.model_config.prediction_length}D_rolling_median=${eval:'${model.model_config.prediction_length}+ ${model.model_config.freq_increm}*3'}D
