defaults:
  - _self_
  - dataset: enedis
  - feature_engineering: default
  - model: tft
  - train: dummy
  - logging: local
  - _constants: constants


hydra:
  run:
    dir: ../outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S} # saves outputs of hydra
