defaults:
  - _self_
  - dataset: enedis
  - model: tft
  - train: dummy
  - _paths: paths


hydra:
  run:
    dir: ../outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S} # saves outputs of hydra
