defaults:
  - _self_
  - dataset: monash_traffic_hourly
  - model: tft
  - train: default


hydra:
  run:
    dir: ../outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S} # saves outputs of hydra
