defaults:
  - load: default
  - _self_

dataset_name: aifluence_public_vrf
load:
  _target_: load.load_data.aifluence_public_histo_vrf
  path: data/idf_mobilites/
  target: nb_vald_total
  weather: null
test_length: 12D
freq: 1D
static_cardinality: [733]
dynamic_cardinality: []
name_feats:
  feat_dynamic_real: []
  feat_static_cat: ["arret"]
  feat_static_real: []
  past_feat_dynamic_real: []
  feat_dynamic_cat : []
