dataset_name: climate_delhi
load:
  _target_: load.load_data.climate
  path: data/climate_delhi/
  target: meantemp
  weather: null
test_length: 114D
freq: 1D
cardinality: []
name_feats:
  feat_dynamic_real: []
  feat_static_cat: []
  feat_static_real: []
  past_feat_dynamic_real: []
