dataset_name: climate_delhi
load:
  _target_: load.load_data.climate
  path: data/climate_delhi/
  target: meantemp
  weather: null
test_length: 114D
freq: 1D
feats:
  num_feat_dynamic_real: 0
  num_feat_static_cat: 0
  num_feat_static_real: 0
