defaults:
  - load: default
  - _self_

dataset_name: enedis
load:
  _target_: load.load_data.enedis
  path: data/enedis/
  target: total_energy
  prediction_length: 6
  freq: ${dataset.freq}
  name_feats: ${dataset.name_feats}

freq_increm: 6  #même ordre de grandeur que prediction length
test_length: 12T
context_length: ${eval:${dataset.load.prediction_length}*4}
freq: 30T
static_cardinality: [12, 2, 8]
dynamic_cardinality: [9]
name_feats:
  feat_for_item_id: ["region", "profil", "power", "power_min", "power_max"]
  feat_dynamic_real: ["temperature", "rainfall", "pressure"]
  feat_static_cat: ["region", "profil", "power"]
  feat_static_real: ["power_min", "power_max"]
  past_feat_dynamic_real: ["soutirage"]
  feat_dynamic_cat : ["barometric_trend"]
