dataset_name: enedis
load:
  _target_: load.load_data.enedis
  path: data/enedis/
  target: total_energy
test_length: 12D
freq: 30T
static_cardinality: []
dynamic_cardinality: []
feats:
  feat_dynamic_real: []
  feat_static_cat: []
  feat_static_real: []
  past_feat_dynamic_real: []
  feat_dynamic_cat : []
