dataset_name: enedis
load:
  _target_: load.load_data.enedis
  path: data/enedis/
  target: total_energy
  weather:
    path_weather: data/all_weather/
    dyn_features:
      - t
      - rr3
      - pmer
    cat_features:
      - cod_tend
    station_name: ORLY
test_length: 12D
freq: 30T
cardinality: [12, 2, 8]
feats:
  num_feat_dynamic_real: 1
  num_feat_static_cat: 3
  num_feat_static_real: 2
