dataset_name: enedis
load:
  _target_: load.load_data.enedis
  path: data/enedis/
  target: total_energy
test_length: 12D
freq: 30T
cardinality: [12, 2, 8]
name_feats:
  feat_dynamic_real: ["soutirage"]
  feat_static_cat: ["region", "profil", "power"]
  feat_static_real: ['power_min', 'power_max']
