dataset_name: energy
load:
  _target_: load.load_data.energy
  path: data/energy/
  target: consommation
  weather:
    path_weather: data/all_weather/
    dyn_features:
      - t
      - rr3
      - pmer
    cat_features:
      - cod_tend
    station_name: ORLY
test_length: 31D
freq: 15T
feats:
  num_feat_dynamic_real: 0
  num_feat_static_cat: 0
  num_feat_static_real: 0
