dataset_name: energy
load:
  _target_: load.load_data.energy
  path: data/energy/
  target: consommation
test_length: 31D
freq: 15T
cardinality: [11]
name_feats:
  feat_dynamic_real: []
  feat_static_cat: ["region"]
  feat_static_real: []
  past_feat_dynamic_real: []
