defaults:
  - load: default
  - _self_

dataset_name: idf_ferro
load:
  _target_: load.load_data.aifluence_public_histo_vrf
  path: data/idf_mobilites
  target: VALD_TOTAL
  prediction_length: ${model.model_config.prediction_length}
  freq: ${dataset.freq}
  start_date: 01/04/2015
  end_date: 31/12/2019
  name_feats: ${dataset.name_feats}
test_length: 12D
freq: 1D
static_cardinality: [688]
dynamic_cardinality: [9]
name_feats:
  feat_dynamic_real: ["temperature", "rainfall", "pressure"]
  feat_static_cat: ["STATION"]
  feat_static_real: []
  past_feat_dynamic_real: ["NB_VALD_AMETHYSTE", "NB_VALD_FGT", "NB_VALD_IMAGINE_R", "NB_VALD_NAVIGO", "NB_VALD_NAVIGO_JOUR","NB_VALD_TST", "NB_VALD_AUTRE",  "amenity_type=Centers", "amenity_type=Education", "amenity_type=Entertainment", "amenity_type=Services", "amenity_type=Sustenance", "amenity_type=Transport", "amenity_type=WorkPlaces"]
  feat_dynamic_cat : ["barometric_trend"]
