dataset_name : monash_traffic_hourly
load:
  _target_: load.load_data.huggingface_dataset
  repository_name: monash_tsf
  dataset_name: traffic_hourly
  freq: ${dataset.freq}
  target: None
freq: 1H
static_cardinality: []
dynamic_cardinality: []
feats:
  feat_dynamic_real: []
  feat_static_cat: []
  feat_static_real: []
  past_feat_dynamic_real: []
  feat_dynamic_cat : []
