dataset_name: weather_paris
load:
  _target_: load.load_data.add_meteo
  path: data/all_weather/
  target: t
test_length: 7D
freq: 15T
feats:
  num_feat_dynamic_real: 2
  num_feat_static_cat: 0
  num_feat_static_real: 0
